### PR TITLE
Mayurigupta13 patch 1

### PR DESCRIPTION
**Pull request by mayurigupta13**
Adding content for Site Recovery. We will need to take out portion of Virtual Machine scale sets to make space for web tier replication with Site Recovery.

VMSS use case is primarily for scale.

### CODE REVIEW

**Comment by DawnmarieDesJardins** [comment]
Thanks Mayuri!  I've alerted the workshop authors to review.  Dawnmarie
@Jeff-Opsgility @mwasham 
Jeff - please assign this pull request to the author for review and advise next steps.

**Comment by bendq** [comment]
Hey Dawnmarie

I've already reviewed this content with Mayuri and am good with this update. She is also going to be making some of the updates to the ppt as well in another update.

**Comment by bendq** [comment]
ok, we'd need this done by the ready time frame for the session

**Comment by mayurigupta13** [comment]
I'm going to create another pull request to complete the story which I walked everyone through.

**Comment by mayurigupta13** [comment]
I have added the portion on Recovery Plan. updated parts of abstract, updated one media file and uploaded one new file.

**Comment by ciphertxt** [comment]
@mayurigupta13 - Is everything you need in this PR? You mentioned another one above but this is the only one submitted so far? My preference would be to have everything in one PR against a new branch (you're targeting master right now).

**Comment by ciphertxt** [comment]
Merged into jan-19-updates branch. Additional updates will be made there.

**Pull request merged**
