### PR TITLE
March 2019 UPDATE

### PR DESCRIPTION
**Pull request by paulopsgility**
Note: The branch name indicates this is a test/fix which is incorrect. This was actually a full update.

### CODE REVIEW

**Comment by DawnmarieDesJardins** [comment]
Email from Won Huh:
Thanks for sharing Dawnmarie, I’ve made my changes here.
https://github.com/Microsoft/MCW-Building-a-resilient-IaaS-architecture/compare/March-2019-TestFix...whuhschool:patch-1 
I’ll validate and confirm other fixes as well.
Won

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility @mwasham @Jeff-Opsgility 
Hello!  SME review has closed.  Please review the feedback above and finalize this update.  Reassign it to me as a reviewer as soon as it's ready for QC/merge.
Thanks, Dawnmarie

**Comment by Jeff-Opsgility** [comment]
Comments incorporated, @DawnmarieDesJardins , Opsgility is finished.

**Comment by DawnmarieDesJardins** [comment]
PR QCd.  Resolves #29 
Merging & updated HTML files.

**Pull request merged**
